services:
  - type: web
    name: puffer-oracle-web
    env: node
    plan: free # THIS IS NOW COMPLETELY FREE
    region: oregon # or your preferred region
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: FITBIT_CLIENT_ID
        sync: false
      - key: FITBIT_CLIENT_SECRET
        sync: false
      - key: ORACLE_PRIVATE_KEY
        sync: false
      - key: MODULE_ADDRESS
        sync: false
      - key: MOVEMENT_NODE_URL
        value: "https://testnet.movementnetwork.xyz/v1"
